name: "Tauri Release"

on:
  push:
    tags:
      - "v*" # Se dispara al pushear un tag, ej: v1.0.0

jobs:
  tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Rust
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: swatinem/rust-cache@v2

      # 4️⃣ Dependencias Linux (GTK / GLib / GObject)
      - name: Install system dependencies (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libgio2.0-dev \
            libgobject-introspection-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            libgdk-pixbuf2.0-dev \
            libsoup2.4-dev \
            librsvg2-dev

      # 5️⃣ Debug PKG_CONFIG (Linux only)
      - name: Debug PKG_CONFIG
        if: matrix.platform == 'ubuntu-latest'
        run: |
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          pkg-config --modversion gobject-2.0
          pkg-config --modversion glib-2.0
          pkg-config --modversion gio-2.0

      # 6️⃣ Instalar dependencias frontend
      - name: Install frontend dependencies
        run: npm install

      # 7️⃣ Build y bundle con Tauri
      - name: Build and bundle app with Tauri
        run: npm run tauri build
        env:
          PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1 # necesario para Linux

      # 8️⃣ Subir artifacts Windows
      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-installers
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe

      # 9️⃣ Subir artifacts Linux
      - name: Upload Linux artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-installers
          path: src-tauri/target/release/bundle/*
