name: "Tauri Release"

on:
  push:
    tags:
      - "v*" # Se ejecuta al pushear un tag como v1.0.0

jobs:
  build:
    name: Build Tauri App
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Rust
      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable

      # 4️⃣ Cache Rust
      - name: Cache Rust
        uses: swatinem/rust-cache@v2

      # 5️⃣ Instalar dependencias específicas según plataforma
      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install gtk+3

      - name: Install WiX Toolset (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          if (Get-Command candle.exe -ErrorAction SilentlyContinue) {
            echo "✅ WiX Toolset already installed. Skipping Chocolatey installation."
          } else {
            echo "⬇️ Installing WiX Toolset..."
            choco install wixtoolset -y
          }

          $wixDir = (Get-ChildItem "C:\Program Files (x86)" -Directory -Filter "WiX Toolset v3.*" | Sort-Object Name -Descending | Select-Object -First 1).FullName
          $wixBin = Join-Path $wixDir "bin"

          if (Test-Path $wixBin) {
            echo "✅ WiX found at: $wixBin"
            echo "$wixBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } else {
            echo "❌ WiX Toolset not found after installation."
            exit 1
          }

      # 6️⃣ Instalar dependencias frontend
      - name: Install frontend dependencies
        run: npm ci

      # 7️⃣ Build de la app con Tauri
      - name: Build and bundle Tauri app
        run: npm run tauri build

      # 8️⃣ Subir artefactos de build (instaladores, binarios, etc.)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/**/*

  # 9️⃣ Crear Release y adjuntar instaladores
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            dist/**/*.msi
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
